### ISSUE TITLE
New 2-member etcd cluster will not allow link to function...

### ISSUE THREAD

**Issue by mitch-shiver** [Scalingo/link#248]
Hi I have a 2-member etcd cluster that from all accounts seems to function normally.  I can write data to it using a key on one member and retrieve that data on the other member with no issues.  It shows both members as healthy.

However after installing link in a similar manner as etcd itself was installed (untar into /tmp folder, verify basic functionality then move into /usr/local/bin) link will not let me add a server to the list or even list the servers as shown in the graphic for the demo. It initially complains "127.0.0.1:1313: connect: connection refused" but once I figured that was because the default host name is 127.0.0.1:1313, I started trying to select localhost vs. IP addresses within the cluster and then 2379 or 2380, nothing worked.  They either gave connection refused or "Error: Unexpected status code: 404". I suspect the port 2379 is the correct one (because it gives 404 error instead of connection refused), but really at this point I am just guessing.  I did realize that I needed to put the 'http://' in front of the IP address (i.e., "/link-client --host http://my_IP:2379 list") but then the error just changed to "Error: Get "http://http//my_IP:2379/ips": dial tcp: lookup http on dns_IP:53: server misbehaving".  If I don't put the "http://" in front of the IP, I get "Error: Unexpected status code: 404", but when I do it doubles like the error above. Please help and/or update the readme to be more comprehensive as to proper installation and addition of servers to the cluster.  Thanks...

I am using etcd 3.4.27 and link 2.0.4.

**Comment by Soulou** [comment]
Thanks for your message @mitch-shiver 

I'm not sure to understand what you're trying precisely. Can you share your setup, which command lines are used, what is started and how?

When you're running `/link-client --host http://my_IP:2379`, you're trying to connect to etcd with the LinK client, it can't work, you have to reach the port of the link-server. 

To get a better understanding, we need more details about your objectives.

**Comment by mitch-shiver** [comment]
Hi @Soulou, Sure.

**What I am trying to do:** use Link for it's advertised purpose, to enable virtual IP support and active/standby of hosts on an IP
**My setup:** 2 linux servers running CentOS7, with a web application exposed on port 8443.  What I want to do is use the active server for the web application and when it goes down for some reason, switch over to the standby server running the same application on the same port
**Command lines used:** It is difficult to share this as I had to make it up as I went along with Link.  I used the very thorough and useful installation instructions for etcd and then validated that it was working with those same very thorough instructions.  When it got to link though, there are no such instructions, just a video showing (I think) two servers connecting using link and etcd to configure for an active/standby setup.  No installation instructions, no details on how to verify it installed correctly, literally just a tar file and a video using it (FWIW, the "link1" and "link2" in the video was also confusing - are those the "link-client" included in the package, just renamed?). So to install it I used the same instructions found in etcd (untar into /tmp folder, verify basic functionality then move into /usr/local/bin), and then to validate it installed correctly I tried to follow and do what the video showed (using link-client instead of link1/link2) and it fails with the errors I point out above.  

It is very possible (probably highly likely in fact) that I am doing the wrong thing, but given the dearth of proper usage instructions that go along with link, I'm really not surprised.  For instance, from your response above, what is "port of the link-server"?  How do I stand up the link server?  I saw nothing describing proper setup of such in the readme.

Thanks for any feedback..
Mitch

**Comment by mitch-shiver** [comment]
Hi, do you need more information?  I am sure I am doing something wrong, but I just can't tell what it is.  Please help...

Thanks!
Mitch

**Comment by Soulou** [comment]
Hi @mitch-shiver thanks for your feedback, we'll update the documentation to fit your need in the coming days it order to make clear what commands to run.

**Comment by mitch-shiver** [comment]
Great!  Can you let me know what I should do to get my instances running?  Or do you think the updated documentation will come along soon enough that I should wait for that instead?  Thanks again...

**Comment by Soulou** [comment]
Hi @mitch-shiver I'm really sorry for the delay of my response.

Unfortunately the policy of our company has changed and this repository is going to be archived since evolution of our infrastructure are going to require a whole new network backend.

Good luck with what you've to do.
