### ISSUE TITLE
ETCD Keepalive time should be configurable by IP (potentially disablable)

### ISSUE THREAD

**Issue by Soulou** [Scalingo/link#84]
Context :

Each IP is being keepalived with ETCD by maintaining a lease. For single-node IP, it's useless and it creates a lot of load on the ETCD clusters.

Action to take:

For IP with only 1 node, we don't need to ping every N seconds ETCD, it should be configurable by IP in order to make it a very long value, or to even disable keepalive lease

**Comment by johnsudaar** [comment]
This feature is nice, but i don't think it solve the issue.

I don't think LinK should depend on client configuration for some internal issues like this. We have all the knowledge needed to make those kind of descision ourself. The solution here should be to check the amount of node that own the IP and slow down the checks if there is only one. This is some internal logic and I don't think that moving the responsibility to the client is a good idea for that.
